### ISSUE TITLE
I'm having trouble getting the translation working

### ISSUE THREAD

**Issue by ArielMAJ** [TheFallen-Cat/VocabiPy#5]
If I remove the translation part, as per shown below, I'm able to get the same output as in the example photo (for english results).
<img width="337" alt="image" src="https://user-images.githubusercontent.com/69123486/186972214-1972b973-5b55-4015-944e-7942a85b26e0.png">

But if I try to run the project as it is, "translator.translate(text=text, dest=language)" raises an exception. By removing the try except, what I get is:

```
Exception in Tkinter callback                                                                                                                                                                               
Traceback (most recent call last):                                                                                                                                                                          
  File "...\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__                                                                                             
    return self.func(*args)                                                                                                                                                                                 
  File "...\VocabiPy\venv\lib\site-packages\customtkinter\widgets\ctk_button.py", line 372, in clicked                                                                     
    self.command()                                                                                                                                                                                          
  File "...\VocabiPy\main.py", line 103, in SearchMeaning                                                                                                                  
    final_meaning = dt.translate(meanings, language_selected)                                                                                                                                               
  File "...\VocabiPy\dictionarymethods.py", line 38, in translate                                                                                                          
    translated_text = translator.translate(text=text, dest=language)                                                                                                                                        
  File "...\VocabiPy\venv\lib\site-packages\googletrans\client.py", line 182, in translate                                                                                 
    data = self._translate(text, dest, src, kwargs)                                                                                                                                                         
  File "...\VocabiPy\venv\lib\site-packages\googletrans\client.py", line 78, in _translate                                                                                 
    token = self.token_acquirer.do(text)                                                                                                                                                                    
  File "...\VocabiPy\venv\lib\site-packages\googletrans\gtoken.py", line 194, in do                                                                                        
    self._update()                                                                                                                                                                                          
  File "...\VocabiPy\venv\lib\site-packages\googletrans\gtoken.py", line 62, in _update                                                                                    
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')                                                                                                                                          
AttributeError: 'NoneType' object has no attribute 'group'                                                                                                                                                  
```

I've made a PR adding a requirements.txt file, maybe you could update it adding the version of googletrans you're using. If it is different, maybe that could be what's causing this problem (considering this project is working properly in your computer).

I'm using Python 3.10.0 on Windows 11, I also had the very same problem when using Python 3.10.4 on WSL Ubuntu-22.04.

**Comment by abhaymakes** [comment]
As far as i think its because of the version of the googletrans i'm using(`3.1.0a0`) as the other versions doesnt seem to work. I'll update the requirements with the module i'm using.

**Comment by abhaymakes** [comment]
Close the issue if it solves the problem. :)

**Comment by ArielMAJ** [comment]
That was it! It works now, ty!
